Scikit-learn is an open-source machine learning library that provides simple and efficient tools for data analysis and modeling. It is built on NumPy, SciPy, and Matplotlib, making it a powerful tool for tasks like classification, regression, clustering, and dimensionality reduction.

In [ ]:
# %conda install scikit-learn

In [1]:
    import sklearn
    print(sklearn.__version__)

1.7.2


In [ ]:
# !pip uninstall scikit-learn # stick with only conda  , both pip and conda would produce conflicts
# !pip uninstall scikit-learn -y            # should be beter 
# this time very slow uninstall, hence keep it

ERROR: Invalid requirement: '#': Expected package name at the start of dependency specifier
    #
    ^


In [ ]:
# !pip install scikit-learn

   ---------------------------------------- 0.0/8.9 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/8.9 MB 6.3 MB/s eta 0:00:02
   ---------- ----------------------------- 2.4/8.9 MB 6.4 MB/s eta 0:00:02
   --------------- ------------------------ 3.4/8.9 MB 5.8 MB/s eta 0:00:01
   ------------------ --------------------- 4.2/8.9 MB 5.4 MB/s eta 0:00:01
   ------------------------ --------------- 5.5/8.9 MB 5.4 MB/s eta 0:00:01
   ------------------------------ --------- 6.8/8.9 MB 5.6 MB/s eta 0:00:01
   ------------------------------------ --- 8.1/8.9 MB 5.7 MB/s eta 0:00:01
   ---------------------------------------- 8.9/8.9 MB 5.6 MB/s  0:00:01
   ---------------------------------------- 0.0/38.7 MB ? eta -:--:--
   - -------------------------------------- 1.6/38.7 MB 8.4 MB/s eta 0:00:05
   -- ------------------------------------- 2.6/38.7 MB 7.2 MB/s eta 0:00:06
   --- ------------------------------------ 3.7/38.7 MB 6.4 MB/s eta 0:00:06
   ----- ----------------

In [3]:
import sklearn

Classification - Logistic Regression Algorithm Example
Logistic Regression is a binary classification algorithm that estimates probabilities of a binary outcome. It's used for problems like spam detection, medical diagnosis, and credit scoring. It's chosen for its simplicity, interpretability, and effectiveness in linearly separable datasets.

In [4]:
# Importing necessary libraries
import numpy                 as     np
import matplotlib.pyplot     as     plt
from sklearn                 import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing   import StandardScaler
from sklearn.linear_model    import LogisticRegression
from sklearn.metrics         import accuracy_score, classification_report

# Load Iris dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target

# Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Standardizing features
scaler  = StandardScaler()
X_train = scaler.fit_transform(X_train) # scalar 
X_test  = scaler.transform(X_test)      # using the same scalar

# Training the logistic regression model
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train) # Training the model

# Making predictions on the testing set
y_pred = log_reg.predict(X_test)

# Evaluating the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0


Classification - KNN Classifier Algorithm Example
K-Nearest Neighbors (KNN) algorithm classifies data points based on the majority class of their nearest neighbors. It's useful for simple classification tasks, particularly when data is not linearly separable or when decision boundaries are complex. It's used in recommendation systems, handwriting recognition, and medical diagnosis.

In [5]:
from sklearn.datasets        import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors       import KNeighborsClassifier

# Load the Iris dataset
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=42)

# Initialize the KNN classifier
knn = KNeighborsClassifier(n_neighbors=3)

# Train the classifier
knn.fit(X_train, y_train)

# Make predictions on the test data
predictions = knn.predict(X_test)

# Evaluate the model
accuracy = knn.score(X_test, y_test)
print("Accuracy:", accuracy)

Accuracy: 1.0


Linear Regression Algorithm Example
Linear Regression fits a linear model to observed data points, predicting continuous outcomes based on input features. It's used when exploring relationships between variables and making predictions. Applications include economics, finance, engineering, and social sciences.

In [ ]:
from sklearn.datasets        import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model    import LinearRegression
from sklearn.metrics         import mean_squared_error

# Load the California Housing dataset
housing = fetch_california_housing()
X_train, X_test, y_train, y_test = train_test_split(housing.data, housing.target, test_size=0.2, random_state=42)

# Initialize the Linear Regression model
lr = LinearRegression()

# Train the model
lr.fit(X_train, y_train)

# Make predictions on the test data
predictions = lr.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, predictions)
print("Mean Squared Error:", mse)

Mean Squared Error: 0.5558915986952425


Clustering - KMeans Algorithm Example
KMeans algorithm partitions data into k clusters based on similarity. It's used for unsupervised clustering tasks like customer segmentation, image compression, and anomaly detection. Ideal when data's structure is unknown but grouping is desired.

In [ ]:
from sklearn.datasets import load_iris
from sklearn.cluster  import KMeans

# Load the Iris dataset
iris = load_iris()

# Initialize the KMeans clustering model
kmeans = KMeans(n_clusters=3)

# Fit the model to the data
kmeans.fit(iris.data)

# Get the cluster labels
cluster_labels = kmeans.labels_

print("Cluster Labels:", cluster_labels)



Cluster Labels: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 1 1 1 1 2 1 1 1 1
 1 1 2 2 1 1 1 1 2 1 2 1 2 1 1 2 2 1 1 1 1 1 2 1 1 1 1 2 1 1 1 2 1 1 1 2 1
 1 2]


c:\Users\zhen-\anaconda3\envs\torch_cuda\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


Dimensionality Reduction - PCA Example
PCA (Principal Component Analysis) reduces the dimensionality of data by finding the most important features. It's used for visualizing high-dimensional data, noise reduction, and speeding up machine learning algorithms. Commonly applied in image processing, genetics, and finance.

In [ ]:
from sklearn.datasets      import load_digits
from sklearn.decomposition import PCA

# Load the digits dataset
digits = load_digits()

# Initialize PCA for dimensionality reduction
pca = PCA(n_components=2)

# Apply PCA to the data
reduced_data = pca.fit_transform(digits.data)

print("Original data shape:", digits.data.shape)
print("Reduced data shape:", reduced_data.shape)

Original data shape: (1797, 64)
Reduced data shape: (1797, 2)


In [ ]:
from sklearn.datasets import load_iris 
iris = load_iris() 

X = iris.data 
y = iris.target 
  
feature_names = iris.feature_names 
target_names = iris.target_names 
  
print("Feature names:", feature_names) 
print("Target names:", target_names) 

print("\nType of X is:", type(X)) 
print("\ndim of X is:", X.ndim) 
print("\nshape of X is:", X.shape)  # <<=============== dim in R

print("\nFirst 5 rows of X:\n", X[:5])

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']

Type of X is: <class 'numpy.ndarray'>

dim of X is: 2

shape of X is: (150, 4)

First 5 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=1)
print("X_train Shape:",  X_train.shape)
print("X_test Shape:", X_test.shape)
print("Y_train Shape:", y_train.shape)
print("Y_test Shape:", y_test.shape)

X_train Shape: (90, 4)
X_test Shape: (60, 4)
Y_train Shape: (90,)
Y_test Shape: (60,)


In [8]:
from sklearn.preprocessing import LabelEncoder

categorical_feature = ['cat', 'dog', 'dog', 'cat', 'bird']

encoder = LabelEncoder()

encoded_feature = encoder.fit_transform(categorical_feature)

print("Encoded feature:", encoded_feature)

Encoded feature: [1 2 2 1 0]
