https://cloud.tencent.com/developer/article/2490262

!conda create -n bioPy312 python=3.12  -y 

%conda is an IPython magic command.
!conda (Shell Command):

In [4]:
import  pandas  as  pd
# 创建 DataFrame
data = {
        'Gene': ['Gene1', 'Gene2'],
        'Cell1': [10, 0],
        'Cell2': [3, 5]
}
df = pd.DataFrame(data)
print(df)

    Gene  Cell1  Cell2
0  Gene1     10      3
1  Gene2      0      5


In [1]:
import  numpy  as  np
# 创建 NumPy 数组
array = np.array([
        [1, 2, 3],
        [4, 5, 6]
])
print(array)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 读取数据
# df = pd.read_csv('data.csv')
# 数据清洗
# df.dropna(inplace=True)

In [2]:
# 数组运算
array = np.array([1, 2, 3])
array = array * 2
print(array)

[2 4 6]


In [3]:
import scanpy as sc
# 读取数据
adata = sc.read_10x_h5('data.h5')
# 预处理
sc.pp.filter_cells(adata, min_genes=200)
sc.pp.normalize_total(adata, target_sum=1e4)

FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'data.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)