https://cloud.tencent.com/developer/article/2490262

!conda create -n bioPy312 python=3.12  -y 

%conda is an IPython magic command.
!conda (Shell Command):

In [1]:
import  pandas  as  pd
# 创建 DataFrame
data = {
        'Gene': ['Gene1', 'Gene2'],
        'Cell1': [10, 0],
        'Cell2': [3, 5]
}
df = pd.DataFrame(data)
print(df)

    Gene  Cell1  Cell2
0  Gene1     10      3
1  Gene2      0      5


In [2]:
import  numpy  as  np
# 创建 NumPy 数组
array = np.array([
        [1, 2, 3],
        [4, 5, 6]
])
print(array)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 读取数据
# df = pd.read_csv('data.csv')
# 数据清洗
# df.dropna(inplace=True)

In [3]:
# 数组运算
array = np.array([1, 2, 3])
array = array * 2
print(array)

[2 4 6]


In [5]:
import scanpy as sc

In [6]:
# 读取数据
adata = sc.read_10x_h5('filtered_feature_bc_matrix.h5')


c:\Users\zhen-\anaconda3\envs\sc_omics\Lib\site-packages\anndata\_core\anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
c:\Users\zhen-\anaconda3\envs\sc_omics\Lib\site-packages\anndata\_core\anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


In [7]:
# 预处理
sc.pp.filter_cells(adata, min_genes=200)
sc.pp.normalize_total(adata, target_sum=1e4)

c:\Users\zhen-\anaconda3\envs\sc_omics\Lib\site-packages\anndata\_core\anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")


In [ ]:

# 识别标记基因
# 识别标记基因
# 识别标记基因
# 识别标记基因
# 识别标记基因


sc.tl.rank_genes_groups(adata, 'leiden', method='t-test')
# 可视化标记基因
sc.pl.rank_genes_groups(adata, n_genes=25, sharey=False)

KeyError: 'leiden'